Repository globalsign/mgo, pull requests merged in 2018-04, with the labels that each got.

#136 Hotfix #120
  README.md
  cluster.go
  cluster_test.go
  session.go
Labels: bug, release

#115 Add signaling support for connection pool waiting
  .gitignore
  cluster.go
  cluster_test.go
  server.go
  session.go
  stats.go
Labels: enhancement, needs stg test

#128 What: add spec for array ops with []uint8 or []byte type
  bson/bson_test.go
  bson/encode.go
Labels: enhancement, needs stg test

#127 bson: Added Encoder and Decoder types for stream encoding/decoding.
  bson/stream.go
  bson/stream_test.go
Labels: enhancement

#141 Minor documentation updates
  README.md
  bson/README.md
  doc.go
Labels: enhancement

#140 Support decimal number type keys in maps
  README.md
  bson/bson_test.go
  bson/decode.go
  bson/encode.go
Labels: enhancement

#149 socket: amortise cost of querying OS time counter
  coarse_time.go
  coarse_time_test.go
  server.go
Labels: enhancement

#144 Implement collation for Collection.Pipe()
  session.go
  session_test.go
Labels: enhancement

#152 Release/r2018.04.23
  .gitignore
  .travis.yml
  README.md
  bson/README.md
  bson/bson_test.go
  bson/decode.go
  bson/encode.go
  bson/stream.go
  bson/stream_test.go
  cluster.go
  cluster_test.go
  coarse_time.go
  coarse_time_test.go
  dbtest/dbserver.go
  dbtest/dbserver_test.go
  doc.go
  example_test.go
  server.go
  session.go
  session_test.go
  socket.go
  stats.go
Labels: enhancement, release

#146 allow ptr in inline structs
  bson/bson.go
  bson/bson_test.go
  bson/encode.go
Labels: enhancement
