Repository globalsign/mgo, pull requests merged in 2018-06, with the labels that each got.

#182 pick: MGO-156 Avoid iter.Next deadlock on dead sockets
  session.go
Labels: bug

#181 Allow passing slice pointer as an interface pointer to Iter.All
  .gitignore
  session.go
  session_test.go
Labels: enhancement

#185 Contributing:findAndModify support writeConcern
  session.go
  session_test.go
Labels: enhancement

#184 Add support for ssl dial string
  example_test.go
  session.go
  session_test.go
Labels: enhancement

#191 Release/r2018.06.15
  README.md
  bson/bson.go
  bson/bson_test.go
  bson/compatibility.go
  bson/encode.go
  cluster.go
  cluster_test.go
  dbtest/dbserver.go
  example_test.go
  export_test.go
  internal/sasl/sasl.go
  internal/scram/scram.go
  server.go
  server_test.go
  session.go
  session_internal_test.go
  session_test.go
  socket.go
Labels: enhancement, release

#129 Add a feature: connect to Unix Domain Sockets
  cluster.go
  server.go
  session.go
  session_test.go
Labels: enhancement

#199 Fix bulk action pool
  bulk.go
  bulk_test.go
  coarse_time_test.go
Labels: bug
