Repository globalsign/mgo, pull requests merged in 2018-10, with the labels that each got.

#258 Changestreams db and cluster level #251
  changestreams.go
  changestreams_test.go
  session.go
Labels: 4.0 feature

#217 decode with inline pointers
  .gitignore
  bson/bson.go
  bson/bson_test.go
  bson/decimal_test.go
  bson/decode.go
Labels: bug

#281 Lazy initialization of coarse time goroutine
  server.go
Labels: enhancement
