Repository globalsign/mgo, pull requests merged in 2018-08, with the labels that each got.

#230 Fix socket race condition
  session.go
  socket.go
Labels: bug

#229 Add 3.6+ user authenticationRestrictions
  README.md
  auth_test.go
  session.go
Labels: 3.6 feature, enhancement

#224 bson: set slice cap for bytes and raw
  bson/decode.go
  bson/decode_test.go
Labels: enhancement

#232 Drop support for old versions (< 3.0)
  README.md
  auth_test.go
  bulk_test.go
  cluster_test.go
  session.go
  session_test.go
  txn/txn_test.go
Labels: enhancement

#233 Improve 3.6 authentication restrictions test
  auth_test.go
Labels: enhancement

#239 Normalize variable name as point receiver
  changestreams.go
Labels: enhancement

#241 Test against Mongo minor releases updates as of Aug 2018
  .travis.yml
Labels: enhancement

#254 Update Travis-CI to run the test on Go 1.11 too
  .travis.yml
  gridfs.go
  session.go
Labels: enhancement

#257 Update CI matrix versions
  .travis.yml
Labels: enhancement

#248 Allow the monitor to be disabled
  dbtest/dbserver.go
Labels: enhancement

#244 Allow wiredTiger engine in dbtest
  dbtest/dbserver.go
  dbtest/dbserver_test.go
Labels: enhancement
