Repository globalsign/mgo, pull requests merged in 2018-05, with the labels that each got.

#158 dbtest: Use os.Kill on Windows instead of os.Interrupt
  dbtest/dbserver.go
Labels: bug

#161 Separate read/write network timeouts
  cluster.go
  cluster_test.go
  export_test.go
  server.go
  server_test.go
  session.go
  session_internal_test.go
  socket.go
Labels: bug, enhancement, needs stg test

#162 add URI options: "w", "j", "wtimeoutMS"
  session.go
  session_test.go
Labels: enhancement

#166 Add Collation support for calling Count() on a Query
  session.go
  session_test.go
Labels: 3.4 feature, enhancement

#171 add NewMongoTimestamp() and MongoTimestamp.Time(),Counter()
  bson/bson.go
  bson/bson_test.go
Labels: enhancement
